# Generated by Django 3.1.2 on 2020-10-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut_admin', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nom_admin', models.CharField(blank=True, max_length=20, null=True)),
                ('apellidop_admin', models.CharField(blank=True, max_length=15, null=True)),
                ('apellidom_admin', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono_admin', models.BigIntegerField(blank=True, null=True)),
                ('correo_admin', models.CharField(blank=True, max_length=30, null=True)),
                ('pass_admin', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BodegaEmpresa',
            fields=[
                ('id_bode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('venta_recibida', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'bodega_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BodegaProductor',
            fields=[
                ('id_bprod', models.BigIntegerField(primary_key=True, serialize=False)),
                ('producto_envasado', models.CharField(blank=True, max_length=2, null=True)),
                ('producto_refrigerado', models.CharField(blank=True, max_length=2, null=True)),
                ('cantidad_disponible', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bodega_productor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteExterno',
            fields=[
                ('rut_cliente', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nom_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('apellidop_cliente', models.CharField(blank=True, max_length=15, null=True)),
                ('apellidom_cliente', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion_residencial', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad_residencial', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_telefonico', models.BigIntegerField(blank=True, null=True)),
                ('pass_cliente', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'cliente_externo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteInterno',
            fields=[
                ('rut_cli_ex', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nom_clien_in', models.CharField(blank=True, max_length=30, null=True)),
                ('apellidop_clien_in', models.CharField(blank=True, max_length=20, null=True)),
                ('apellidom_clientein', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_clien_in', models.CharField(blank=True, max_length=1, null=True)),
                ('ciudad_clien_in', models.CharField(blank=True, max_length=40, null=True)),
                ('correo_clien_in', models.CharField(blank=True, max_length=40, null=True)),
                ('numero_cliente_in', models.BigIntegerField(blank=True, null=True)),
                ('pass_cliente', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'cliente_interno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('rut_consultor', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nom_consultor', models.CharField(blank=True, max_length=30, null=True)),
                ('apellidop_consultor', models.CharField(blank=True, max_length=15, null=True)),
                ('apellidom_consultor', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_consultor', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_consultor', models.BigIntegerField(blank=True, null=True)),
                ('pass_consultor', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'consultor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nume_contrato', models.BigIntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('vigencia', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoVenta',
            fields=[
                ('id_cont', models.BigIntegerField(primary_key=True, serialize=False)),
                ('num_contrato_venta', models.BigIntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('vigencia', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'contrato_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_deta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('productos', models.CharField(blank=True, max_length=300, null=True)),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
                ('subtotal', models.BigIntegerField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_estado', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfertaProduc',
            fields=[
                ('codigo_op', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'oferta_produc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfertaTransp',
            fields=[
                ('cod_ot', models.FloatField(primary_key=True, serialize=False)),
                ('precio_oferta', models.FloatField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'oferta_transp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('medio_pago', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('numero_transaccion', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoVenta',
            fields=[
                ('cod_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('comision_empresa', models.BigIntegerField(blank=True, null=True)),
                ('costo_transportista', models.BigIntegerField(blank=True, null=True)),
                ('costo_aduana', models.BigIntegerField(blank=True, db_column='costo__aduana', null=True)),
                ('costo_servicio', models.BigIntegerField(blank=True, null=True)),
                ('costo_total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedido_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcesoInterno',
            fields=[
                ('codigo_proceso', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'proceso_interno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcesoVenta',
            fields=[
                ('id_proceso', models.BigIntegerField(primary_key=True, serialize=False)),
                ('informacion_venta', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'proceso_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(blank=True, max_length=30, null=True)),
                ('precio_prod', models.BigIntegerField(blank=True, null=True)),
                ('peso_prod', models.FloatField(blank=True, null=True)),
                ('calidad_prod', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('rut_produc', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nom_produc', models.CharField(blank=True, max_length=20, null=True)),
                ('apellidop_produc', models.CharField(blank=True, max_length=15, null=True)),
                ('apellidom_produc', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion_produc', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad_produc', models.CharField(blank=True, max_length=40, null=True)),
                ('telefono_produc', models.BigIntegerField(blank=True, null=True)),
                ('correo_produc', models.CharField(blank=True, max_length=30, null=True)),
                ('pass_produc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'productor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelSoliProducto',
            fields=[
                ('id_rel_soli_produc', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
                ('tipo_distribucion', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'rel_soli_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id_reporte', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numero_reporte', models.BigIntegerField(blank=True, null=True)),
                ('descripcion_reporte', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'reportes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_rol', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id_saldo', models.BigIntegerField(blank=True, null=True)),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
                ('tipo_distribucion', models.CharField(blank=True, max_length=1, null=True)),
                ('saldo_id', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'saldo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeccionEsta',
            fields=[
                ('id_sesta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'seccion_esta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudVenta',
            fields=[
                ('id_soli', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numero_soli', models.BigIntegerField(blank=True, null=True)),
                ('direccion_entrega', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'solicitud_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id_subasta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('requisito_subasta', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'subasta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('rut_transp', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_transp', models.CharField(blank=True, max_length=20, null=True)),
                ('apellidop_transp', models.CharField(blank=True, max_length=15, null=True)),
                ('apellidom_transp', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_trasp', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono_transo', models.BigIntegerField(blank=True, null=True)),
                ('patente_vehiculo', models.CharField(blank=True, max_length=30, null=True)),
                ('capacidad_carga', models.BigIntegerField(blank=True, null=True)),
                ('refrigeracion', models.CharField(blank=True, max_length=2, null=True)),
                ('pass_transp', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'transportista',
                'managed': False,
            },
        ),
    ]
